name: Sync LGTM.com alerts

on:
  pull_request:
  push:

jobs:
  lgtm-sync:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Get LGTM sarif
      - uses: devexpress/github-actions/lgtm@v1
        with:
          repository: DevExpress/DevExtreme

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: lgtm.sarif
