name: Sync LGTM.com alerts

on:
  schedule:
    - cron: '30 1 * * *'

jobs:
  lgtm-sync:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: devexpress/github-actions/lgtm
        with:
          repository: DevExpress/DevExtreme
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: lgtm.sarif
