name: Sync LGTM.com alerts

on:
  pull_request:
  push:

jobs:
  lgtm-sync:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Get LGTM sarif
        # uses: devexpress/github-actions/lgtm@main
        uses: ./.github/wokflows/lgtm-get.yml
        with:
          repository: DevExpress/DevExtreme

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: lgtm.sarif

      - name: Display Info
        run: |
          echo HOHOHO
